### ISSUE TITLE
JS and PHP API keys are different

### ISSUE THREAD

**Issue by friek108** [pinfirestudios/yii2-bugsnag#5]
When I set up bugsnag, it requested I set up 2 x projects, one for php and one for js. And the API keys are different for both but with this component, can only set up 1 api key (so I can't use both at the same time).

**Comment by jcherniak** [comment]
We piped both JS and PHP using the same API keys.  I saw no issue using the same one.  I think the only thing it might affect is syntax highlighting, but I don't even think that was an issue.
